DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  admin_id INTEGER DEFAULT 1,
  order_timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
  order_pending BOOLEAN NOT NULL DEFAULT FALSE,
  order_ready BOOLEAN NOT NULL DEFAULT FALSE
);
