DROP TABLE IF EXISTS ordered_items CASCADE;
CREATE TABLE ordered_items (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES items(id) ON DELETE CASCADE,
  size_id INTEGER REFERENCES cup_sizes(id) ON DELETE CASCADE,
  quantity SMALLINT NOT NULL DEFAULT 0,
  price INTEGER NOT NULL DEFAULT 0
);
